# Generated by Django 3.2.19 on 2023-07-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMF_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMF_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=150)),
                ('data', models.FloatField()),
            ],
        ),
    ]
